version: '3'

services:

  node1:
    image: two_miners_test:1.0
    container_name: node1
    environment:
      - LOCAL_IP=192.168.1.1
    ports:
      - 5679:5678
    privileged: true
    volumes:
      - ./main.py:/run/main.py
      - ./network.py:/run/network.py
      - ./blockchain_structures.py:/run/blockchain_structures.py
      - ./random_functions.py:/run/random_functions.py
      - ./tests.py:/run/tests.py
      - ./data:/run/data
      - ./peers:/run/peers
    command: >
        bash -c "python3 main.py"
    networks:
      static-network:
        ipv4_address: 192.168.1.1


  node2:
    image: two_miners_test:1.0
    container_name: node2
    environment:
      - LOCAL_IP=192.168.1.2
    ports:
      - 5680:5678
    privileged: true
    volumes:
      - ./main.py:/run/main.py
      - ./network.py:/run/network.py
      - ./blockchain_structures.py:/run/blockchain_structures.py
      - ./random_functions.py:/run/random_functions.py
      - ./tests.py:/run/tests.py
      - ./data:/run/data
      - ./peers:/run/peers
    command: >
        bash -c "python3 main.py"
    networks:
      static-network:
        ipv4_address: 192.168.1.2


  node3:
    image: two_miners_test:1.0
    container_name: node3
    environment:
      - LOCAL_IP=192.168.1.3
    ports:
      - 5681:5678
    privileged: true
    volumes:
      - ./main.py:/run/main.py
      - ./network.py:/run/network.py
      - ./blockchain_structures.py:/run/blockchain_structures.py
      - ./random_functions.py:/run/random_functions.py
      - ./tests.py:/run/tests.py
      - ./data:/run/data
      - ./peers:/run/peers
    command: >
        bash -c "python3 main.py"
    networks:
      static-network:
        ipv4_address: 192.168.1.3


  node4:
    image: two_miners_test:1.0
    container_name: node4
    environment:
      - LOCAL_IP=192.168.1.4
    ports:
      - 5682:5678
    privileged: true
    volumes:
      - ./main.py:/run/main.py
      - ./network.py:/run/network.py
      - ./blockchain_structures.py:/run/blockchain_structures.py
      - ./random_functions.py:/run/random_functions.py
      - ./tests.py:/run/tests.py
      - ./data:/run/data
      - ./peers:/run/peers
    command: >
        bash -c "python3 main.py"
    networks:
      static-network:
        ipv4_address: 192.168.1.4


  node5:
    image: two_miners_test:1.0
    container_name: node5
    environment:
      - LOCAL_IP=192.168.1.5
    ports:
      - 5683:5678
    privileged: true
    volumes:
      - ./main.py:/run/main.py
      - ./network.py:/run/network.py
      - ./blockchain_structures.py:/run/blockchain_structures.py
      - ./random_functions.py:/run/random_functions.py
      - ./tests.py:/run/tests.py
      - ./data:/run/data
      - ./peers:/run/peers
    command: >
        bash -c "python3 main.py"
    networks:
      static-network:
        ipv4_address: 192.168.1.5


  node6:
    image: two_miners_test:1.0
    container_name: node6
    environment:
      - LOCAL_IP=192.168.1.6
    ports:
      - 5684:5678
    privileged: true
    volumes:
      - ./main.py:/run/main.py
      - ./network.py:/run/network.py
      - ./blockchain_structures.py:/run/blockchain_structures.py
      - ./random_functions.py:/run/random_functions.py
      - ./tests.py:/run/tests.py
      - ./data:/run/data
      - ./peers:/run/peers
    command: >
        bash -c "python3 main.py"
    networks:
      static-network:
        ipv4_address: 192.168.1.6


  node7:
    image: two_miners_test:1.0
    container_name: node7
    environment:
      - LOCAL_IP=192.168.1.7
    ports:
      - 5685:5678
    privileged: true
    volumes:
      - ./main.py:/run/main.py
      - ./network.py:/run/network.py
      - ./blockchain_structures.py:/run/blockchain_structures.py
      - ./random_functions.py:/run/random_functions.py
      - ./tests.py:/run/tests.py
      - ./data:/run/data
      - ./peers:/run/peers
    command: >
        bash -c "python3 main.py"
    networks:
      static-network:
        ipv4_address: 192.168.1.7


  node8:
    image: two_miners_test:1.0
    container_name: node8
    environment:
      - LOCAL_IP=192.168.1.8
    ports:
      - 5686:5678
    privileged: true
    volumes:
      - ./main.py:/run/main.py
      - ./network.py:/run/network.py
      - ./blockchain_structures.py:/run/blockchain_structures.py
      - ./random_functions.py:/run/random_functions.py
      - ./tests.py:/run/tests.py
      - ./data:/run/data
      - ./peers:/run/peers
    command: >
        bash -c "python3 main.py"
    networks:
      static-network:
        ipv4_address: 192.168.1.8


  node9:
    image: two_miners_test:1.0
    container_name: node9
    environment:
      - LOCAL_IP=192.168.1.9
    ports:
      - 5687:5678
    privileged: true
    volumes:
      - ./main.py:/run/main.py
      - ./network.py:/run/network.py
      - ./blockchain_structures.py:/run/blockchain_structures.py
      - ./random_functions.py:/run/random_functions.py
      - ./tests.py:/run/tests.py
      - ./data:/run/data
      - ./peers:/run/peers
    command: >
        bash -c "python3 main.py"
    networks:
      static-network:
        ipv4_address: 192.168.1.9


  node10:
    image: two_miners_test:1.0
    container_name: node10
    environment:
      - LOCAL_IP=192.168.1.10
    ports:
      - 5688:5678
    privileged: true
    volumes:
      - ./main.py:/run/main.py
      - ./network.py:/run/network.py
      - ./blockchain_structures.py:/run/blockchain_structures.py
      - ./random_functions.py:/run/random_functions.py
      - ./tests.py:/run/tests.py
      - ./data:/run/data
      - ./peers:/run/peers
    command: >
        bash -c "python3 main.py"
    networks:
      static-network:
        ipv4_address: 192.168.1.10


  node11:
    image: two_miners_test:1.0
    container_name: node11
    environment:
      - LOCAL_IP=192.168.1.11
    ports:
      - 5689:5678
    privileged: true
    volumes:
      - ./main.py:/run/main.py
      - ./network.py:/run/network.py
      - ./blockchain_structures.py:/run/blockchain_structures.py
      - ./random_functions.py:/run/random_functions.py
      - ./tests.py:/run/tests.py
      - ./data:/run/data
      - ./peers:/run/peers
    command: >
        bash -c "python3 main.py"
    networks:
      static-network:
        ipv4_address: 192.168.1.11


  node12:
    image: two_miners_test:1.0
    container_name: node12
    environment:
      - LOCAL_IP=192.168.1.12
    ports:
      - 5690:5678
    privileged: true
    volumes:
      - ./main.py:/run/main.py
      - ./network.py:/run/network.py
      - ./blockchain_structures.py:/run/blockchain_structures.py
      - ./random_functions.py:/run/random_functions.py
      - ./tests.py:/run/tests.py
      - ./data:/run/data
      - ./peers:/run/peers
    command: >
        bash -c "python3 main.py"
    networks:
      static-network:
        ipv4_address: 192.168.1.12


  node13:
    image: two_miners_test:1.0
    container_name: node13
    environment:
      - LOCAL_IP=192.168.1.13
    ports:
      - 5691:5678
    privileged: true
    volumes:
      - ./main.py:/run/main.py
      - ./network.py:/run/network.py
      - ./blockchain_structures.py:/run/blockchain_structures.py
      - ./random_functions.py:/run/random_functions.py
      - ./tests.py:/run/tests.py
      - ./data:/run/data
      - ./peers:/run/peers
    command: >
        bash -c "python3 main.py"
    networks:
      static-network:
        ipv4_address: 192.168.1.13


  node14:
    image: two_miners_test:1.0
    container_name: node14
    environment:
      - LOCAL_IP=192.168.1.14
    ports:
      - 5692:5678
    privileged: true
    volumes:
      - ./main.py:/run/main.py
      - ./network.py:/run/network.py
      - ./blockchain_structures.py:/run/blockchain_structures.py
      - ./random_functions.py:/run/random_functions.py
      - ./tests.py:/run/tests.py
      - ./data:/run/data
      - ./peers:/run/peers
    command: >
        bash -c "python3 main.py"
    networks:
      static-network:
        ipv4_address: 192.168.1.14


  node15:
    image: two_miners_test:1.0
    container_name: node15
    environment:
      - LOCAL_IP=192.168.1.15
    ports:
      - 5693:5678
    privileged: true
    volumes:
      - ./main.py:/run/main.py
      - ./network.py:/run/network.py
      - ./blockchain_structures.py:/run/blockchain_structures.py
      - ./random_functions.py:/run/random_functions.py
      - ./tests.py:/run/tests.py
      - ./data:/run/data
      - ./peers:/run/peers
    command: >
        bash -c "python3 main.py"
    networks:
      static-network:
        ipv4_address: 192.168.1.15


  node16:
    image: two_miners_test:1.0
    container_name: node16
    environment:
      - LOCAL_IP=192.168.1.16
    ports:
      - 5694:5678
    privileged: true
    volumes:
      - ./main.py:/run/main.py
      - ./network.py:/run/network.py
      - ./blockchain_structures.py:/run/blockchain_structures.py
      - ./random_functions.py:/run/random_functions.py
      - ./tests.py:/run/tests.py
      - ./data:/run/data
      - ./peers:/run/peers
    command: >
        bash -c "python3 main.py"
    networks:
      static-network:
        ipv4_address: 192.168.1.16


  node17:
    image: two_miners_test:1.0
    container_name: node17
    environment:
      - LOCAL_IP=192.168.1.17
    ports:
      - 5695:5678
    privileged: true
    volumes:
      - ./main.py:/run/main.py
      - ./network.py:/run/network.py
      - ./blockchain_structures.py:/run/blockchain_structures.py
      - ./random_functions.py:/run/random_functions.py
      - ./tests.py:/run/tests.py
      - ./data:/run/data
      - ./peers:/run/peers
    command: >
        bash -c "python3 main.py"
    networks:
      static-network:
        ipv4_address: 192.168.1.17


  node18:
    image: two_miners_test:1.0
    container_name: node18
    environment:
      - LOCAL_IP=192.168.1.18
    ports:
      - 5696:5678
    privileged: true
    volumes:
      - ./main.py:/run/main.py
      - ./network.py:/run/network.py
      - ./blockchain_structures.py:/run/blockchain_structures.py
      - ./random_functions.py:/run/random_functions.py
      - ./tests.py:/run/tests.py
      - ./data:/run/data
      - ./peers:/run/peers
    command: >
        bash -c "python3 main.py"
    networks:
      static-network:
        ipv4_address: 192.168.1.18


  node19:
    image: two_miners_test:1.0
    container_name: node19
    environment:
      - LOCAL_IP=192.168.1.19
    ports:
      - 5697:5678
    privileged: true
    volumes:
      - ./main.py:/run/main.py
      - ./network.py:/run/network.py
      - ./blockchain_structures.py:/run/blockchain_structures.py
      - ./random_functions.py:/run/random_functions.py
      - ./tests.py:/run/tests.py
      - ./data:/run/data
      - ./peers:/run/peers
    command: >
        bash -c "python3 main.py"
    networks:
      static-network:
        ipv4_address: 192.168.1.19


  node20:
    image: two_miners_test:1.0
    container_name: node20
    environment:
      - LOCAL_IP=192.168.1.20
    ports:
      - 5698:5678
    privileged: true
    volumes:
      - ./main.py:/run/main.py
      - ./network.py:/run/network.py
      - ./blockchain_structures.py:/run/blockchain_structures.py
      - ./random_functions.py:/run/random_functions.py
      - ./tests.py:/run/tests.py
      - ./data:/run/data
      - ./peers:/run/peers
    command: >
        bash -c "python3 main.py"
    networks:
      static-network:
        ipv4_address: 192.168.1.20




networks:
  static-network:
    ipam:
      config:
        - subnet: 192.168.0.0/16
          gateway: 192.168.0.1

 # docker-compose -f emm.yaml up -d
