def write_yaml(main_num):
    print("version: '3'\n")
    print('services:\n')

    print("  experimenter" + ":")
    print("    image: two_miners_test:1.0 ")
    print("    container_name: experimenter")
    print("    environment:")
    print("      - LOCAL_IP=192.168.1." + str(0))
    print("    ports:")
    print("      - " + str(5679 + 0 - 1) + ":5678")
    print("    privileged: true")
    print("    volumes:")
    print("      - ./main" + str(main_num)  + ".py:/run/main.py")
    print("      - ./network.py:/run/network.py")
    print("      - ./blockchain_structures.py:/run/blockchain_structures.py")
    print("      - ./random_functions.py:/run/random_functions.py")
    print("      - ./tests.py:/run/tests.py")
    print("      - ./data:/run/data")
    print("      - ./peers:/run/peers")
    print("      - ./experimenter.py:/run/experimenter.py")
    print("    command: >")
    print('        bash -c "python3 experimenter.py"')
    print("    networks:")
    print("      static-network:")
    print("        ipv4_address: 192.168.1." + str(0))
    print("\n")

    for i in range(1, 4):    # 3 users
        print("  node" + str(i) + ":")
        print("    image: two_miners_test:1.0 ")
        print("    depends_on:")
        print("      - experimenter")
        print("    container_name: node" + str(i))
        print("    environment:")
        print("      - LOCAL_IP=192.168.1." + str(i))
        print("    ports:")
        print("      - " + str(5679 + i - 1) + ":5678")
        print("    privileged: true")
        print("    volumes:")
        print("      - ./main.py:/run/main.py")
        print("      - ./main" + str(main_num)  + ".py:/run/main.py")
        print("      - ./network.py:/run/network.py")
        print("      - ./blockchain_structures.py:/run/blockchain_structures.py")
        print("      - ./random_functions.py:/run/random_functions.py")
        print("      - ./tests.py:/run/tests.py")
        print("      - ./data:/run/data")
        print("      - ./peers:/run/peers")
        print("    command: >")
        print('        bash -c "python3 main.py"')
        print("    networks:")
        print("      static-network:")
        print("        ipv4_address: 192.168.1." + str(i))
        print("\n")

    print("\n")
    print("networks: ")
    print("  static-network:")
    print("    ipam:")
    print("      config:")
    print("        - subnet: 192.168.0.0/16")
    print("          gateway: 192.168.0.1")

    print("\n # docker-compose -f emm.yaml up -d")


write_yaml(8)
